version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth_service
    command: ["gunicorn", "auth.wsgi:application", "--bind", "0.0.0.0:8000"]
    volumes:
      - .:/usr/src/app  # Mount the entire project directory
      - static_volume:/usr/src/app/staticfiles 

    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    container_name: auth_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

volumes:
  postgres_data:
  static_volume: